import Head from "next/head";
import Image from "next/image";
import Profilepic from "../image/profile.jpg";
import Opener from "../image/opener.jpg";
import Kids from "../image/kids-paint.jpg";
import Coffee from "../image/coffecup.jpg";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    // <div className={styles.container}>
    <>
      <Head>
        <title>Gratulerer Med Dagen!</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Gratulerer med 69-års dagen Pappa!</h1>
        <Image src={Profilepic} alt='Profilepic' width={250} />

        <p className={styles.description}>Men husk, alder er bare et tall!</p>
        <p>Men bursdagsgave blir man aldri for gammel for!</p>
        <p>Men den kommer ikke i dag, men i stedet får du vite hva du får</p>
        <ul>
          <li>Sånn boksåpner, som du kan knipe på.</li>
          <li>Et blide av alle 4 barna, du kan henge på veggen!</li>
          <li>En kopp du kan drikke kaffi av.</li>
        </ul>

        <div className={styles.gift}>
          <Image src={Opener} alt='lid opener' width={100} />
          <Image src={Kids} alt='kidsa' width={100} height={100} />
          <Image src={Coffee} alt='coffeecup' width={100} />
        </div>
      </main>
      <footer className={styles.footer}>
        Made with love by: Andreas Takvam 07.11.2022
      </footer>
    </>
    // </div>
  );
}
